### ISSUE TITLE
it could be a good idea to delete your keystore file from a public repo...

### ISSUE THREAD

**Issue by cloudybyte** [gymh/GymHerzo-Android#16]
everyone could sign apps with your name lmao

**Comment by philippd1** [comment]
No. that statement is invalid 🤣
As stated in the readme, the public keystore is only used when folks want to develop the app and install it on their own device but don't know/ want to generate their own JKS.
The production keystore is of couse held private.
Moreover, AAB signing with PlayStore managed keys will be used in future releases.

appreciate the thoughts, but totally invalid.
closing issue.
